### ISSUE TITLE
Remove rdma-core pinning

### ISSUE THREAD

**Issue by pentschev** [conda-forge/ucx-split-feedstock#145]
### Comment:

After `rdma-core>49.0` is released, remove:

```
      ignore_run_exports:
        - rdma-core
```

and 

```
      run:
        - rdma-core >={{ rdma_core }}  # [linux64]
```

With https://github.com/conda-forge/rdma-core-feedstock/pull/13 having set `max_pin=None` it should suffice for UCX to simply rely on rdma-core's unrestricted upper bound. However, to avoid the need to mark rdma-core 49.0 build 0 as broken, we can wait for the next rdma-core release to remove the entries above.

**Comment by jakirkham** [comment]
We are now on `rdma-core` `50`: https://github.com/conda-forge/ucx-split-feedstock/pull/154

So think this should be possible now

**Comment by pentschev** [comment]
Looks like I forgot to close this but it was already done in https://github.com/conda-forge/ucx-split-feedstock/pull/142 .

**Comment by jakirkham** [comment]
Thought the idea of this issue was to drop these lines?

https://github.com/conda-forge/ucx-split-feedstock/blob/1c50eab5ca4bdb8d4d54e5bb11bb34a8fa8f852f/recipe/meta.yaml#L23-L24

https://github.com/conda-forge/ucx-split-feedstock/blob/1c50eab5ca4bdb8d4d54e5bb11bb34a8fa8f852f/recipe/meta.yaml#L44-L45

**Comment by pentschev** [comment]
Whelp [missing :face_palm: emoji]. Submitted https://github.com/conda-forge/ucx-split-feedstock/pull/161 to address this now.
